export const CHANGE_DIFFICULTY = 'CHANGE_DIFFICULTY'
export const CHANGE_PAGE = 'CHANGE_PAGE'
export const SELECT_AUDIOCHALLENGE = 'SELECT_AUDIOCHALLENGE'
export const SELECT_SPRINT = 'SELECT_SPRINT'