export const CHANGE_DIFFICULTY = 'CHANGE_DIFFICULTY';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const SELECT_AUDIOCHALLENGE = 'SELECT_AUDIOCHALLENGE';
export const SELECT_SPRINT = 'SELECT_SPRINT';
export const FROM_TEXTBOOK = 'FROM_TEXTBOOK';
export const FROM_MENU = 'FROM_MENU';
export const CHANGE_SERIA = 'CHANGE_SERIA';
export const TITLE_CHANGE = 'TITLE_CHANGE';
