export const ADD_CASH = 'ADD_CASH'
export const GET_CASH = 'GET_CASH'
export const ADD_USER = 'ADD_USER'
export const GET_USER = 'GET_USER'
export const CHANGE_DIFFICULTY = 'CHANGE_DIFFICULTY'
export const CHANGE_PAGE = 'CHANGE_PAGE'